// AUTO-GENERATED by scripts/sync-portfolio.ts — do not edit manually.
// Run: npm run sync

import type { Project } from "@/types/project"

export const projects: Project[] = [
  {
    slug: "learnpod",
    title: "LearnPod",
    tagline:
      "Personal learning system that turns saved content into spaced-repetition pods",
    description: `LearnPod is a Progressive Web App that solves the bookmark graveyard problem: you save Instagram reels, articles, and videos with the intent to learn from them, then never look at them again. LearnPod captures that content as atomic Pods (one idea each), groups related Pods into Modules (mini-courses), and surfaces them back through an interleaved review queue with XP, streaks, and progress tracking — so saved content actually becomes knowledge.

The app is backed by an Obsidian vault as the source of truth: Pods are authored as Markdown files with frontmatter, enriched with research and notes inside Obsidian, then synced into the app at build time via a custom content pipeline. The result is a learner-owned, plain-text knowledge base that doubles as a polished study app on any device.`,
    category: "featured",
    status: "active",
    techStack: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Zustand",
      "next-pwa",
      "gray-matter",
      "Obsidian",
      "Vercel",
    ],
    repoUrl: "https://github.com/MattAtencio/learnpod",
    images: {
      thumbnail: "/images/projects/learnpod-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Vault-as-source-of-truth pipeline: capture and edit Pods in Obsidian, study them in the app",
      "Atomic Pods + Modules content model that scales from one-off captures to structured mini-courses",
      "Interleaved review queue that mixes Pods across Modules to fight the spacing/forgetting curve",
      "XP, streaks with forgiveness windows, and progress tracking for habit formation",
      "Build-time content sync from Markdown + frontmatter into typed app data — no database required",
      "Installable PWA with offline support so review sessions work on a subway or a plane",
      "Designed for self-directed learners who want to retain what they save instead of letting it rot in bookmarks",
    ],
    isPublic: false,
    startDate: "2026-03",
    featured: true,
  },
  {
    slug: "enterprise-integration",
    title: "Enterprise Integration Architecture",
    tagline:
      "Cloud-native mortgage platform serving millions of B2B and B2C users",
    description: `At Sagent, I architect and develop cloud-native microservices for a 24/7 consumer mortgage platform. Key initiatives include modernizing authentication from single-IDP to a secure multi-IDP OIDC proxy architecture, building payment processor integrations, and optimizing observability systems.

This work spans the full integration lifecycle — from vendor discovery and architecture design through go-live and production support — across identity providers, payment processors, and servicing platforms.`,
    category: "professional",
    status: "active",
    techStack: [
      "C#",
      ".NET",
      "Azure",
      "Microservices",
      "OAuth/OIDC",
      "Okta",
      "Auth0",
      "Terraform",
    ],
    images: {
      thumbnail: "/images/projects/integration-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Modernized authentication to secure multi-IDP OIDC proxy architecture",
      "Scaled client onboarding to 4–5 concurrent launches via automation",
      "Reduced telemetry costs by 50% through optimized observability strategy",
      "Established Sev 1 incident response standards and SLA frameworks",
    ],
    businessContext:
      "Consumer mortgage platforms require 24/7 availability, strict regulatory compliance, and seamless integrations across identity, payments, and servicing vendors.",
    isPublic: false,
    startDate: "2021-08",
    featured: true,
  },
  {
    slug: "fitops",
    title: "FitOps",
    tagline:
      "All-in-one operations platform for personal trainers and fitness studios",
    description: `FitOps is a full-stack business operations platform that gives independent personal trainers and small fitness studios a single product to run their entire business — instead of stitching together a CRM, scheduling tool, comms inbox, education platform, and analytics suite.

It ships role-based portals for managers, trainers, students, and clients, plus a kiosk mode for in-studio check-in. Trainers manage clients, schedules, payroll, communications, and content from one workspace; students get a dedicated learning portal with certificates and workshops; managers get analytics and member journey insights. The platform integrates with MindBody, SendGrid, Sentry, and Supabase, and runs background work through a BullMQ + Upstash Redis worker.`,
    category: "professional",
    status: "active",
    techStack: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "BullMQ",
      "Upstash Redis",
      "NextAuth",
      "Tailwind CSS",
      "Jest",
      "Playwright",
    ],
    repoUrl: "https://github.com/MattAtencio/FitOps",
    images: {
      thumbnail: "/images/projects/fitops-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Role-based portals for managers, trainers, students, and clients, plus a studio kiosk mode",
      "Integrated CRM, scheduling, payroll, referrals, and reporting in a single operational workspace",
      "Education Portal with certificates, teaching practice, and workshops — powered by a student-facing portal and analytics dashboard",
      "Communications Inbox with PII redaction, audio transcription, and conversation threading",
      "Member Journey timelines and visual flow builder using @xyflow/react for client lifecycle automation",
      "BullMQ + Upstash Redis worker pipeline for background jobs (notifications, transcription, syncs)",
      "MindBody API integration for studios migrating off legacy booking systems",
      "Comprehensive Jest + Playwright + MSW test suite covering API routes, UI flows, and worker logic",
    ],
    businessContext:
      "Targets independent personal trainers and small fitness studios who need an integrated platform instead of paying for and stitching together a half-dozen separate SaaS tools.",
    isPublic: false,
    startDate: "2025-09",
    featured: true,
  },
  {
    slug: "anagram-chain",
    title: "Anagram Chain",
    tagline:
      "Unscramble words to build chains",
    description: `Anagram Chain combines word unscrambling with chain-building mechanics. Players solve anagrams in sequence, with each word connecting to the next.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "JavaScript",
      "PWA",
      "CSS Modules",
    ],
    liveUrl: "https://anagram.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/anagram-chain",
    images: {
      thumbnail: "/images/projects/anagram-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Seeded daily puzzle selection",
      "Canvas-based confetti celebrations",
      "Procedural audio with Web Audio API",
    ],
    isPublic: true,
    startDate: "2025-01",
    featured: false,
  },
  {
    slug: "flowgrid",
    title: "FlowGrid",
    tagline:
      "Connect color pairs on a grid without crossing paths",
    description: `FlowGrid challenges players to connect matching color pairs on a grid without crossing any paths. Features daily puzzles and increasing difficulty levels.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "JavaScript",
      "PWA",
      "CSS Modules",
    ],
    liveUrl: "https://flowgrid.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/flowgrid",
    images: {
      thumbnail: "/images/projects/flowgrid-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Procedurally generated puzzles with difficulty scaling",
      "Smooth touch-based path drawing",
      "PWA with offline play",
    ],
    isPublic: true,
    startDate: "2025-01",
    featured: false,
  },
  {
    slug: "forge-and-field",
    title: "Forge & Field",
    tagline:
      "Craft gear and send heroes on quests",
    description: `An idle/incremental game where players collect resources, craft weapons and armor, recruit heroes, and send them on expeditions with turn-based combat. Features offline progression, a prestige system, and rotating seasonal events.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "React 19",
      "PWA",
      "CSS Modules",
    ],
    liveUrl: "https://forge.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/forge-and-field",
    roadmapUrl: "/projects/forge-and-field/roadmap",
    images: {
      thumbnail: "/images/projects/forge-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Turn-based combat with 4 hero archetypes and gear crafting",
      "Tiered chest system with Green/Blue/Purple rarity and guaranteed drops",
      "Offline progression and prestige/rebirth system",
      "Rotating seasonal events with exclusive rewards",
    ],
    isPublic: true,
    startDate: "2025-01",
    featured: false,
    hasCaseStudy: true,
  },
  {
    slug: "kids-corner",
    title: "Kids Corner",
    tagline:
      "Educational game suite for kids ages 2-6",
    description: `Kids Corner is a collection of five interactive learning games designed for children ages 2-6. The suite includes Color Mixer (color blending), Count Along (number counting with themed object sets), Letter Land (alphabet exploration), Sunny Days (weather and daily routines), and Alpha Dots (connect-the-dots alphabet).

All games share a core framework (@kids-games/core) with pre-generated TTS audio featuring kid-friendly persona voices, celebration animations, and consistent UI patterns. Accessible through a central hub at kids.mattatencio.com.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "React 19",
      "TypeScript",
      "OpenAI TTS",
      "PWA",
      "Tailwind CSS",
    ],
    liveUrl: "https://kids.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/kids-hub",
    images: {
      thumbnail: "/images/projects/kids-corner-thumb.png",
      screenshots: [],
    },
    highlights: [
      "5 games sharing a core framework with pre-generated TTS persona voices",
      "Age-appropriate UI with large touch targets and celebration animations",
      "Central hub with game launcher and progress tracking",
    ],
    isPublic: true,
    startDate: "2026-03",
    featured: false,
  },
  {
    slug: "lexle",
    title: "Lexle",
    tagline:
      "Daily word puzzle in the style of Wordle",
    description: `Lexle is a daily word-guessing game inspired by Wordle. Players have six attempts to guess a hidden five-letter word, with color-coded feedback after each guess indicating correct letters and positions.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "JavaScript",
      "PWA",
      "CSS Modules",
    ],
    liveUrl: "https://lexle.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/lexle",
    images: {
      thumbnail: "/images/projects/lexle-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Daily puzzle rotation with seeded word selection",
      "Color-coded letter feedback with keyboard tracking",
      "Installable PWA with offline support",
    ],
    isPublic: true,
    startDate: "2025-03",
    featured: false,
  },
  {
    slug: "mahjong-path",
    title: "Mahjong Path",
    tagline:
      "Strategic tile-matching with bot opponents",
    description: `A Mahjong tile-matching game with three difficulty levels of bot opponents. Features hand evaluation, pattern matching, and a learn mode for newcomers. Includes beginner, intermediate, and master-level AI using shared utility functions.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "React 19",
      "TypeScript",
      "PWA",
    ],
    liveUrl: "https://mahjong.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/mahjong-path",
    images: {
      thumbnail: "/images/projects/mahjong-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Three AI difficulty tiers with shared bot utility system",
      "Learn mode with guided tutorials",
      "Hand evaluation and scoring engine",
    ],
    isPublic: true,
    startDate: "2026-03",
    featured: false,
  },
  {
    slug: "minesweeper",
    title: "Minesweeper",
    tagline:
      "Modern Minesweeper with haptics and audio",
    description: `A modern Minesweeper PWA with three difficulty levels, haptic vibration patterns, and synthesized sound effects. Features cascade reveals, particle explosions, chord reveal mechanics, and a responsive dark-themed UI.`,
    category: "games",
    status: "active",
    techStack: [
      "JavaScript",
      "HTML5",
      "CSS3",
      "Web Audio API",
      "PWA",
    ],
    liveUrl: "https://minesweeper.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/minesweeper",
    images: {
      thumbnail: "/images/projects/minesweeper-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Haptic feedback with custom vibration patterns",
      "Synthesized audio effects via Web Audio API",
      "Three difficulty levels with particle effects and screen shake",
    ],
    isPublic: true,
    startDate: "2025-01",
    featured: false,
  },
  {
    slug: "solitaire",
    title: "Solitaire",
    tagline:
      "Classic Klondike Solitaire with drag & drop",
    description: `A fully-featured digital Klondike Solitaire game with smooth drag-and-drop card mechanics, undo functionality, move tracking, timer, and auto-complete. Features a polished dark UI with gold accents optimized for both desktop and mobile.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "React 19",
      "PWA",
      "CSS Modules",
    ],
    liveUrl: "https://solitaire.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/solitaire",
    images: {
      thumbnail: "/images/projects/solitaire-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Smooth drag-and-drop with visual feedback",
      "Undo history, auto-complete, and double-tap moves",
      "Installable PWA with offline support",
    ],
    isPublic: true,
    startDate: "2025-01",
    featured: false,
  },
  {
    slug: "spectrum",
    title: "Spectrum",
    tagline:
      "Color-matching word puzzle game",
    description: `Spectrum is a daily puzzle game where players sort words along a color gradient. Built as a Progressive Web App with daily puzzle rotation using seeded randomness.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "JavaScript",
      "PWA",
      "CSS Modules",
    ],
    liveUrl: "https://spectrum.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/spectrum-game",
    images: {
      thumbnail: "/images/projects/spectrum-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Daily puzzle rotation with seeded randomness",
      "Installable PWA with offline support",
      "Mobile-first design optimized for touch",
    ],
    isPublic: true,
    startDate: "2025-01",
    featured: false,
  },
  {
    slug: "wikichain",
    title: "WikiChain",
    tagline:
      "Wikipedia word-chain challenge",
    description: `WikiChain is a daily word game where players navigate between Wikipedia topics by finding connecting words. Tests vocabulary and lateral thinking.`,
    category: "games",
    status: "active",
    techStack: [
      "Next.js",
      "JavaScript",
      "PWA",
      "CSS Modules",
    ],
    liveUrl: "https://wikichain.mattatencio.com",
    repoUrl: "https://github.com/MattAtencio/wiki-chain",
    images: {
      thumbnail: "/images/projects/wikichain-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Wikipedia-inspired word chains with daily rotation",
      "Hint system for accessibility",
      "Procedural sound effects via Web Audio API",
    ],
    isPublic: true,
    startDate: "2025-01",
    featured: false,
  },
  {
    slug: "claude-framework",
    title: "Claude Framework",
    tagline:
      "Autonomous development framework turning Claude Code into a full engineering team",
    description: `A meta-tooling framework that extends Claude Code with 36+ reusable skills, 7 specialized review agents, automated communication pipelines, and an Obsidian-backed knowledge graph. Orchestrates daily workflows from morning briefing through end-of-day wrap with parallel agent execution, Slack/Discord integration, and persistent memory across sessions.

Built as a living system that evolves with each project — skills are composed, agents are dispatched in parallel, and session knowledge compounds through structured vault notes with wikilinks and frontmatter.`,
    category: "tools",
    status: "active",
    techStack: [
      "Claude Code",
      "Python",
      "Bash",
      "Slack API",
      "Discord API",
      "Obsidian",
      "YAML",
      "JSON",
    ],
    images: {
      thumbnail: "/images/projects/claude-framework-thumb.png",
      screenshots: [],
    },
    highlights: [
      "36+ composable skills with YAML frontmatter, context isolation, and tool restrictions",
      "7 specialized review agents for architecture, security, product, QA, and UI/UX",
      "Automated Slack/Discord intake pipelines with classification and GitHub routing",
      "Obsidian knowledge graph with session notes, MOCs, and cross-project connection tracking",
      "Zero-dashboard deployment automation with GitHub push, Vercel/Supabase provisioning, Cloudflare DNS, and Slack approval gates",
    ],
    businessContext:
      "Solo developer productivity multiplier — automates the overhead of managing 14+ active projects, from morning planning through deployment and daily documentation.",
    isPublic: false,
    startDate: "2025-03",
    featured: true,
    hasCaseStudy: true,
  },
  {
    slug: "homelab",
    title: "Homelab",
    tagline:
      "Infrastructure-as-code and hardware dashboard for a self-hosted home server lab",
    description: `Monorepo for a personal homelab environment. Includes a React hardware inventory dashboard with network topology visualization, plus infrastructure-as-code for provisioning and service deployment.

Phased rollout from NAS foundation through AI memory layer, with security policies, containerized services, and zero-trust remote access.`,
    category: "tools",
    status: "active",
    techStack: [
      "React 18",
      "Vite",
      "Express",
      "LowDB",
      "Docker Compose",
      "Terraform",
      "Ansible",
      "Pi-hole",
      "NetAlertX",
      "n8n",
    ],
    images: {
      thumbnail: "/images/projects/homelab-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Grouped network topology view with interactive device tree",
      "Phased IaC rollout for self-hosted services",
      "Containerized deployment with zero-trust remote access",
      "Infra-ops system with agents, skills, scripts, and SSH guardrails for safe remote ops",
      "Docker stacks for Pi-hole, NetAlertX, and n8n automation",
      "Self-hosted n8n automation playbook with 14 starter workflows",
    ],
    isPublic: false,
    startDate: "2026-02",
    featured: false,
  },
  {
    slug: "infra",
    title: "Infra",
    tagline:
      "Terraform IaC for game sites, DNS, and GitHub repo configuration",
    description: `Infrastructure-as-code repo that codifies the deployment substrate for a portfolio of small game sites and tools. A reusable Terraform game-site module standardizes hosting, DNS, and repo wiring so new games can ship with a single module call.

Cloudflare DNS records and GitHub repository configuration are managed declaratively, eliminating dashboard drift and making infrastructure changes reviewable in PRs.`,
    category: "tools",
    status: "active",
    techStack: [
      "Terraform",
      "Cloudflare",
      "GitHub",
      "HCL",
    ],
    images: {
      thumbnail: "/images/projects/infra-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Reusable Terraform game-site module for one-call deployment of new games",
      "Cloudflare DNS managed as code across all project domains",
      "GitHub repository configuration codified — settings, branch protection, secrets",
      "Single source of truth for hosting, DNS, and repo state across the portfolio",
    ],
    isPublic: false,
    startDate: "2026-02",
    featured: false,
  },
  {
    slug: "signal-forge",
    title: "Signal Forge",
    tagline:
      "ML-driven crypto research, backtesting, and paper-trading platform",
    description: `Signal Forge is a full-stack quantitative research and paper-trading platform for cryptocurrency. It pairs an XGBoost prediction pipeline with a strict walk-forward backtesting engine, a portfolio tracker, and a trading engine that generates signals and manages simulated positions — separating long-term BTC holds from shorter-term altcoin swing trades.

The system is built as a multi-service architecture: a Python/FastAPI backend with SQLAlchemy 2.0 and JWT auth handles ingestion, modeling, and the API; a React 18 + Chart.js frontend provides the user-facing dashboard with batch backtesting and per-trade equity curves; and a Streamlit + Plotly app provides deep analytics for model and strategy research. Trading defaults to virtual mode by design — real-money integration requires explicit sign-off — and all external APIs are rate-limited and gracefully degrade when unavailable.`,
    category: "tools",
    status: "active",
    techStack: [
      "Python 3.12",
      "FastAPI",
      "SQLAlchemy 2.0",
      "Pydantic v2",
      "Alembic",
      "XGBoost",
      "Prophet",
      "Pandas",
      "APScheduler",
      "React 18",
      "Chart.js",
      "Streamlit",
      "Plotly",
      "Docker Compose",
      "CoinGecko API",
      "Binance API",
    ],
    repoUrl: "https://github.com/MattAtencio/signal-forge",
    images: {
      thumbnail: "/images/projects/signal-forge-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Walk-forward backtesting engine with strict no-lookahead time partitioning",
      "XGBoost prediction pipeline with engineered features including MACD normalization and Binance funding rates",
      "Trading engine with signal generation, smart exits, and position management — virtual-by-default for safety",
      "Portfolio tracker with performance metrics, allocation analysis, and rebalancing logic",
      "Batch backtest UI for sweeping parameters across symbols and timeframes, with per-trade breakdown and equity curve visualization",
      "Real-time CoinGecko + Binance market data pipeline with rate limiting, caching, and graceful degradation",
      "Three-surface architecture: FastAPI backend, React operator dashboard, and Streamlit research notebook",
      "JWT auth with bcrypt, scoped access controls on user-owned portfolio and trade data",
    ],
    businessContext:
      "A quantitative, risk-managed approach to crypto investing: separate BTC long-term holds from altcoin swing trades, validate every strategy with walk-forward backtests before any real capital is involved.",
    isPublic: false,
    startDate: "2025-05",
    featured: false,
  },
  {
    slug: "unified-dashboard",
    title: "Unified Dashboard",
    tagline:
      "One-screen CLI for usage, cost, and security across every hosting and SaaS provider you use",
    description: `Unified Dashboard is a terminal-based command center that pulls usage, cost, and security signals from every hosting and SaaS provider in a solo developer's stack and renders them as a single glanceable view. Instead of opening 15 browser tabs each morning to check whether anything is on fire or burning budget, you run one command and see it all.

It ships as an installable Node CLI built around a small ServiceProvider interface: each provider is a self-contained module that fetches metrics from a REST API and reports a normalized status. The core handles polling, caching, alert evaluation against per-service thresholds, and rendering — collapsed (one line per service), expanded (full metrics), drill-down (single service deep view), JSON (for piping into jq), or watch mode (continuous refresh).`,
    category: "tools",
    status: "active",
    techStack: [
      "TypeScript",
      "Node.js",
      "Commander",
      "Chalk",
      "cli-table3",
      "REST APIs",
    ],
    repoUrl: "https://github.com/MattAtencio/unified-dashboard",
    images: {
      thumbnail: "/images/projects/unified-dashboard-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Single-command terminal view aggregating 15+ providers: Vercel, Cloudflare, GitHub, Anthropic, OpenAI, Supabase, Sentry, Slack, Twilio, SendGrid, Railway, Upstash, n8n, Figma, GoDaddy",
      "Pluggable ServiceProvider interface — adding a new provider is one file plus a config entry",
      "Multiple output modes: collapsed, expanded, drill-down, JSON pipe, and continuous --watch",
      "Per-service warning and critical alert thresholds defined in a central config registry",
      "Polling layer with caching and --no-cache override to balance freshness vs. API rate limits",
      "Token-scoped access — each provider documents the minimum scopes it needs, secrets stay in .env",
      "Built for solo operators managing many small projects across many vendors at once",
    ],
    isPublic: false,
    startDate: "2026-03",
    featured: false,
  },
  {
    slug: "vault",
    title: "Vault",
    tagline:
      "Personal finance PWA with AI insights and bank integration",
    description: `Vault is a personal finance application that aggregates bank accounts via Plaid, categorizes transactions using Claude AI, and delivers weekly financial insights. Built as a Turborepo monorepo with an Express 5 API backend and React 19 PWA frontend.

Features include automated transaction sync, AI-powered categorization, push notifications, and gamified financial goal tracking.`,
    category: "tools",
    status: "active",
    techStack: [
      "React 19",
      "TypeScript",
      "Express 5",
      "Prisma",
      "PostgreSQL",
      "Redis",
      "Plaid API",
      "Claude API",
      "Tailwind CSS",
      "Turborepo",
    ],
    repoUrl: "https://github.com/MattAtencio/vault",
    images: {
      thumbnail: "/images/projects/vault-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Plaid integration for bank account aggregation and transaction sync",
      "Claude AI-powered transaction categorization and weekly financial insights",
      "Turborepo monorepo with Express 5 API and React 19 PWA",
      "BullMQ job queue with Redis for background processing",
      "Financial goal tracking with CRUD, push notifications, and cash flow summaries",
      "Recurring transaction templates with frequency scheduling and forecast integration",
    ],
    businessContext:
      "Consolidates personal finance data from multiple bank accounts with AI-driven insights to improve financial awareness and decision-making.",
    isPublic: false,
    startDate: "2026-02",
    featured: false,
  },
  {
    slug: "yoga-dashboard",
    title: "Yoga Dashboard",
    tagline:
      "Studio operations prototype with MindBody API mock",
    description: `A prototype dashboard for yoga studio operations, featuring a complete mock of the MindBody public API. Built as a proof-of-concept for the FitOps platform.`,
    category: "tools",
    status: "maintained",
    techStack: [
      "FastAPI",
      "React",
      "Python",
    ],
    images: {
      thumbnail: "/images/projects/yoga-thumb.png",
      screenshots: [],
    },
    highlights: [
      "Full MindBody API mock for development",
      "End-to-end studio operations prototype",
      "Foundation for FitOps platform development",
    ],
    isPublic: false,
    startDate: "2024-06",
    featured: false,
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}

export function getFeaturedProjects(): Project[] {
  return projects.filter((p) => p.featured)
}

export function getProjectsByCategory(
  category: Project["category"]
): Project[] {
  return projects.filter((p) => p.category === category)
}

export function getGameProjects(): Project[] {
  return projects.filter((p) => p.category === "games")
}
